const WHATSAPP_NUMBER='2348166352271';
const money=value=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(value);
const waIcon=()=>`<svg class="wa-icon" viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M19.11 17.27c-.26-.13-1.55-.76-1.79-.85-.24-.09-.41-.13-.59.13-.17.26-.67.85-.83 1.02-.15.17-.3.2-.56.07-.26-.13-1.08-.4-2.06-1.27-.76-.68-1.27-1.52-1.42-1.78-.15-.26-.02-.4.11-.53.12-.12.26-.3.39-.46.13-.15.17-.26.26-.43.09-.17.04-.33-.02-.46-.07-.13-.59-1.42-.8-1.94-.21-.51-.43-.44-.59-.45h-.5c-.17 0-.46.07-.7.33-.24.26-.91.89-.91 2.17 0 1.28.94 2.52 1.07 2.69.13.17 1.84 2.81 4.46 3.94.62.27 1.11.43 1.49.55.63.2 1.2.17 1.65.1.5-.07 1.55-.63 1.77-1.24.22-.61.22-1.13.15-1.24-.06-.11-.24-.17-.5-.3z"/><path fill="currentColor" d="M16.04 3.2A12.64 12.64 0 0 0 5.18 22.29L3.39 28.8l6.67-1.75a12.64 12.64 0 1 0 5.98-23.85zm0 22.98c-1.84 0-3.64-.49-5.2-1.42l-.37-.22-3.96 1.04 1.06-3.86-.24-.4a10.31 10.31 0 1 1 8.71 4.86z"/></svg>`;
function waUrl(message){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`}
function safe(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function effectivePrice(product,quantity){const qty=Math.max(1,Number(quantity||1));const qualifies=product.wholesaleMOQ&&product.wholesalePrice&&qty>=product.wholesaleMOQ;return {unitPrice:qualifies?product.wholesalePrice:product.retailPrice,qualifies}}
function orderMessage(product,quantity){const qty=Math.max(1,Number(quantity||1));const pricing=effectivePrice(product,qty);const campaign=product.campaigns?.length?` Campaign: ${product.campaigns.join(', ')}.`:'';const priceLine=pricing.unitPrice?` Current displayed unit price: ${money(pricing.unitPrice)}${pricing.qualifies?' wholesale':''}.`:'';return `Hello Royal Molson. I want ${product.name} (${product.modelCode}). Quantity: ${qty}.${campaign}${priceLine} Please confirm availability, colour/size selection and delivery cost.`}
function productMeta(product){const parts=[];if(product.capacity)parts.push(product.capacity);if(product.description)parts.push(product.description);if(product.colours?.length)parts.push(`Colours: ${product.colours.join(', ')}`);return parts.join(' · ')}
function wholesalePrompt(product){if(product.wholesaleMOQ&&product.wholesalePrice)return `Buy ${product.wholesaleMOQ} or more for ${money(product.wholesalePrice)} each.`;return 'Wholesale pricing available on request.'}
function cardTemplate(product){const retail=product.retailPrice?`<span class="price current-price">${money(product.retailPrice)}</span><span class="price-note current-tier">retail price</span>`:`<span class="price current-price">Price on request</span><span class="price-note current-tier">confirm on WhatsApp</span>`;const visual=product.imageUrl?`<a href="product.html?slug=${encodeURIComponent(product.slug)}"><img src="${safe(product.imageUrl)}?auto=format&w=700&fit=max" alt="${safe(product.name)}" loading="lazy"></a>`:`<a href="product.html?slug=${encodeURIComponent(product.slug)}"><div class="mini-flask" aria-hidden="true"></div></a>`;return `<article class="product-card" data-model="${safe(product.modelCode)}"><div class="product-visual">${visual}</div><span class="model">${safe(product.modelCode)}</span><h3><a href="product.html?slug=${encodeURIComponent(product.slug)}">${safe(product.name)}</a></h3><p class="product-meta">${safe(productMeta(product))}</p><div class="price-row">${retail}</div><p class="wholesale-hint">${safe(wholesalePrompt(product))}</p><div class="qty-control"><input class="qty" type="number" min="1" value="1" aria-label="Quantity"><span class="price-note">units</span></div><div class="pricing-status" aria-live="polite"></div><div class="card-actions"><a class="button button-primary buy-card" href="#">${waIcon()}Chat to buy</a><a class="button button-outline" href="product.html?slug=${encodeURIComponent(product.slug)}">View product</a></div></article>`}
function updateCardPricing(card,product){const qty=Math.max(1,Number(card.querySelector('.qty')?.value||1));const pricing=effectivePrice(product,qty);const priceEl=card.querySelector('.current-price');const tierEl=card.querySelector('.current-tier');const status=card.querySelector('.pricing-status');if(pricing.unitPrice){priceEl.textContent=money(pricing.unitPrice);tierEl.textContent=pricing.qualifies?'wholesale price per unit':'retail price'}if(product.wholesaleMOQ&&product.wholesalePrice){if(pricing.qualifies){status.innerHTML=`<strong>Wholesale unlocked.</strong> ${qty} units × ${money(product.wholesalePrice)} = ${money(qty*product.wholesalePrice)}`;status.classList.add('qualified')}else{const left=product.wholesaleMOQ-qty;status.textContent=`Add ${left} more ${left===1?'unit':'units'} to unlock ${money(product.wholesalePrice)} wholesale price each.`;status.classList.remove('qualified')}}else status.textContent=''}
function bindCards(root,list){root.querySelectorAll('.product-card').forEach((card,i)=>{const product=list[i];const qty=card.querySelector('.qty');updateCardPricing(card,product);qty.addEventListener('input',()=>updateCardPricing(card,product));card.querySelector('.buy-card').addEventListener('click',e=>{e.preventDefault();window.open(waUrl(orderMessage(product,qty.value)),'_blank','noopener')})})}
function renderProducts(list,target){const root=document.querySelector(target);if(!root)return;if(!list.length){root.innerHTML='<p class="product-meta">Products will appear here when published in the store backend.</p>';return}root.innerHTML=list.map(cardTemplate).join('');bindCards(root,list)}
async function loadCatalog(){try{const query=`*[_type == "product" && status == "visible"] | order(category->sortOrder asc, sortOrder asc, name asc){_id,name,modelCode,"slug":slug.current,capacity,description,features,colours,sizes,retailPrice,wholesalePrice,wholesaleMOQ,stock,featured,"category":category->slug.current,"brand":brand->title,"campaigns":promotions[]->title,"imageUrl":mainImage.asset->url}`;const list=await window.rmgSanityQuery(query);const byCategory=slug=>list.filter(p=>p.category===slug);renderProducts(byCategory('back-to-school'),'#school-products');renderProducts(byCategory('water-flasks'),'#water-product-grid');renderProducts(byCategory('food-flasks'),'#food-product-grid');renderProducts(byCategory('water-bottles'),'#water-bottle-grid');renderProducts(byCategory('cutlery'),'#cutlery-product-grid')}catch(error){console.error(error);document.querySelectorAll('.product-grid').forEach(root=>root.innerHTML='<p class="product-meta">The product catalog could not load. Please use WhatsApp to order while we reconnect the catalog.</p>')}}
loadCatalog();
const generalMessages={general:'Hello Royal Molson. I want to buy a product. Please help me choose the right model, colour and quantity.',mama:"Hello Royal Molson. I am interested in the Mama's Promise Back-to-School Lunch Pack. Please send the available models, colours, current price and delivery options."};document.querySelectorAll('[data-wa]').forEach(link=>{const key=link.dataset.wa;link.href=waUrl(generalMessages[key]||generalMessages.general);link.target='_blank';link.rel='noopener';if(link.classList.contains('wa-with-icon')||link.classList.contains('floating-wa'))link.insertAdjacentHTML('afterbegin',waIcon())});
const quoteForm=document.querySelector('#quote-form');quoteForm?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(quoteForm);window.open(waUrl(`Hello Royal Molson. I want a wholesale quote. Product/model: ${data.get('product')}. Quantity: ${data.get('quantity')}. Delivery city: ${data.get('city')}. Please confirm the applicable wholesale price, MOQ and delivery terms.`),'_blank','noopener')});
const navToggle=document.querySelector('.nav-toggle');const mainNav=document.querySelector('.main-nav');navToggle?.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open))});mainNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mainNav.classList.remove('open');navToggle?.setAttribute('aria-expanded','false')}));const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();