const WHATSAPP_NUMBER='2348166352271';
const money=value=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(value);
function waUrl(message){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`}
function safe(v=''){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function orderMessage(product,quantity){const qty=Number(quantity||1);const campaign=product.campaigns?.length?` Campaign: ${product.campaigns.join(', ')}.`:'';const buyingMode=qty>1?'Please confirm the best retail/wholesale price available for this quantity.':'Please confirm availability, colour options and delivery cost.';return `Hello Royal Molson. I want ${product.name} (${product.modelCode}). Quantity: ${qty}.${campaign} ${buyingMode}`}
function productMeta(product){const parts=[];if(product.capacity)parts.push(product.capacity);if(product.description)parts.push(product.description);if(product.colours?.length)parts.push(`Colours: ${product.colours.join(', ')}`);return parts.join(' · ')}
function cardTemplate(product){const price=product.retailPrice?`<span class="price">${money(product.retailPrice)}</span><span class="price-note">retail price</span>`:`<span class="price">Price on request</span><span class="price-note">confirm on WhatsApp</span>`;const visual=product.imageUrl?`<img src="${safe(product.imageUrl)}?auto=format&w=700&fit=max" alt="${safe(product.name)}" loading="lazy">`:`<div class="mini-flask" aria-hidden="true"></div>`;return `<article class="product-card" data-model="${safe(product.modelCode)}"><div class="product-visual">${visual}</div><span class="model">${safe(product.modelCode)}</span><h3>${safe(product.name)}</h3><p class="product-meta">${safe(productMeta(product))}</p><div class="price-row">${price}</div><div class="qty-control"><input class="qty" type="number" min="1" value="1" aria-label="Quantity"><span class="price-note">units</span></div><div class="card-actions"><a class="button button-primary buy-card" href="#">Chat to buy</a><a class="button button-outline quote-card-action" href="#">Wholesale</a></div></article>`}
function bindCards(root,list){root.querySelectorAll('.product-card').forEach((card,i)=>{const product=list[i];const qty=card.querySelector('.qty');card.querySelector('.buy-card').addEventListener('click',e=>{e.preventDefault();window.open(waUrl(orderMessage(product,qty.value)),'_blank','noopener')});card.querySelector('.quote-card-action').addEventListener('click',e=>{e.preventDefault();window.open(waUrl(`Hello Royal Molson. I am interested in wholesale pricing for ${product.name} (${product.modelCode}). Quantity: ${qty.value}. Please send the applicable wholesale price, MOQ and delivery terms.`),'_blank','noopener')})})}
function renderProducts(list,target){const root=document.querySelector(target);if(!root)return;if(!list.length){root.innerHTML='<p class="product-meta">Products will appear here when published in the store backend.</p>';return}root.innerHTML=list.map(cardTemplate).join('');bindCards(root,list)}
async function loadCatalog(){try{const query=`*[_type == "product" && status == "visible"] | order(category->sortOrder asc, sortOrder asc, name asc){_id,name,modelCode,capacity,description,features,colours,retailPrice,wholesalePrice,wholesaleMOQ,stock,featured,"category":category->slug.current,"brand":brand->title,"campaigns":promotions[]->title,"imageUrl":mainImage.asset->url}`;const list=await window.rmgSanityQuery(query);const byCategory=slug=>list.filter(p=>p.category===slug);renderProducts(byCategory('back-to-school'),'#school-products');renderProducts(byCategory('water-flasks'),'#water-product-grid');renderProducts(byCategory('food-flasks'),'#food-product-grid');renderProducts(byCategory('water-bottles'),'#water-bottle-grid');renderProducts(byCategory('cutlery'),'#cutlery-product-grid')}catch(error){console.error(error);document.querySelectorAll('.product-grid').forEach(root=>root.innerHTML='<p class="product-meta">The product catalog could not load. Please use WhatsApp to order while we reconnect the catalog.</p>')}}
loadCatalog();
const generalMessages={general:'Hello Royal Molson. I want to buy a product. Please help me choose the right model, colour and quantity.',mama:"Hello Royal Molson. I am interested in the Mama's Promise Back-to-School Lunch Pack. Please send the available models, colours, current price and delivery options."};document.querySelectorAll('[data-wa]').forEach(link=>{const key=link.dataset.wa;link.href=waUrl(generalMessages[key]||generalMessages.general);link.target='_blank';link.rel='noopener'});
const quoteForm=document.querySelector('#quote-form');quoteForm?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(quoteForm);window.open(waUrl(`Hello Royal Molson. I want a wholesale quote. Product/model: ${data.get('product')}. Quantity: ${data.get('quantity')}. Delivery city: ${data.get('city')}. Please confirm the applicable wholesale price, MOQ and delivery terms.`),'_blank','noopener')});
const navToggle=document.querySelector('.nav-toggle');const mainNav=document.querySelector('.main-nav');navToggle?.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open))});mainNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mainNav.classList.remove('open');navToggle?.setAttribute('aria-expanded','false')}));document.querySelector('#year').textContent=new Date().getFullYear();